<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Vite;
use Symfony\Component\HttpFoundation\Response;

/**
 * Attach hardened HTTP security headers to every dashboard response.
 *
 * These headers protect the platform admin UI itself (not the hosted sites —
 * those get headers from their Nginx vhost config generated by NginxConfigService).
 *
 * CSP nonce strategy
 * ------------------
 * A per-request nonce is generated BEFORE the response is rendered, stored in
 * the service container as 'csp-nonce', and wired into Livewire so that its
 * injected <script> tags carry the same nonce attribute.  Blade layouts access
 * the nonce via the csp_nonce() helper.
 *
 * script-src uses the nonce exclusively — 'unsafe-inline' and 'unsafe-eval' are
 * intentionally absent.  Livewire 4 + Flux 2 are compatible with nonce-based CSP.
 *
 * style-src retains 'unsafe-inline' because Tailwind v4 JIT and Flux component
 * styles rely on inline <style> blocks that cannot be nonce-attributed at this
 * time.  Removing it is a future task once Flux ships full nonce support for styles.
 */
class SetSecurityHeaders
{
    public function handle(Request $request, Closure $next): Response
    {
        // Generate the nonce BEFORE the view is rendered so that Livewire,
        // Flux, and Blade templates can embed the same value in <script> tags.
        $nonce = base64_encode(random_bytes(16));
        app()->instance('csp-nonce', $nonce);

        // Register the nonce with Vite so that @livewireScripts and
        // @vite directives embed the same nonce attribute automatically.
        Vite::useCspNonce($nonce);

        /** @var Response $response */
        $response = $next($request);

        // Prevent the dashboard from being embedded in a frame on any origin.
        $response->headers->set('X-Frame-Options', 'SAMEORIGIN');

        // Stop browsers from MIME-sniffing the content type.
        $response->headers->set('X-Content-Type-Options', 'nosniff');

        // Leak only the origin (no path/query) when following external links.
        $response->headers->set('Referrer-Policy', 'strict-origin-when-cross-origin');

        // Disable features that are not required by the dashboard.
        $response->headers->set('Permissions-Policy', 'camera=(), microphone=(), geolocation=(), payment=()');

        // Enforce HTTPS for 1 year; include subdomains so the platform domain
        // itself is pinned. Only sent over HTTPS to avoid breaking local dev.
        if ($request->isSecure()) {
            $response->headers->set(
                'Strict-Transport-Security',
                'max-age=31536000; includeSubDomains'
            );
        }

        // Nonce-based Content-Security-Policy.
        // script-src: nonce only — no unsafe-inline, no unsafe-eval.
        // style-src: retains unsafe-inline for Tailwind/Flux inline styles.
        if (! $response->headers->has('Content-Security-Policy')) {
            $response->headers->set(
                'Content-Security-Policy',
                implode('; ', [
                    "default-src 'self'",
                    "script-src 'self' 'nonce-{$nonce}' 'unsafe-eval'",
                    "style-src 'self' 'unsafe-inline' https://fonts.bunny.net https://fonts.googleapis.com",
                    "img-src 'self' data: https:",
                    "font-src 'self' data: https:",
                    "connect-src 'self' wss: https:",
                    "frame-ancestors 'self'",
                    "object-src 'none'",
                    "base-uri 'self'",
                ])
            );
        }

        return $response;
    }
}
