<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * Attach hardened HTTP security headers to every dashboard response.
 *
 * These headers protect the Pixelkraft admin UI itself (not the hosted sites —
 * those get headers from their Nginx vhost config generated by NginxConfigService).
 */
class SetSecurityHeaders
{
    public function handle(Request $request, Closure $next): Response
    {
        /** @var Response $response */
        $response = $next($request);

        // Prevent the dashboard from being embedded in a frame on any origin.
        $response->headers->set('X-Frame-Options', 'SAMEORIGIN');

        // Stop browsers from MIME-sniffing the content type.
        $response->headers->set('X-Content-Type-Options', 'nosniff');

        // Leak only the origin (no path/query) when following external links.
        $response->headers->set('Referrer-Policy', 'strict-origin-when-cross-origin');

        // Disable features that are not required by the dashboard.
        $response->headers->set('Permissions-Policy', 'camera=(), microphone=(), geolocation=(), payment=()');

        // Enforce HTTPS for 1 year; include subdomains so the Pixelkraft domain
        // itself is pinned. Only sent over HTTPS to avoid breaking local dev.
        if ($request->isSecure()) {
            $response->headers->set(
                'Strict-Transport-Security',
                'max-age=31536000; includeSubDomains'
            );
        }

        // Basic Content-Security-Policy for the dashboard.
        // 'unsafe-inline' on style-src is required by Tailwind/Livewire inline styles.
        // The nonce approach is a future improvement; this default-src restriction
        // still provides meaningful XSS mitigation on the admin interface.
        if (! $response->headers->has('Content-Security-Policy')) {
            $response->headers->set(
                'Content-Security-Policy',
                implode('; ', [
                    "default-src 'self'",
                    "script-src 'self' 'unsafe-inline' 'unsafe-eval'",
                    "style-src 'self' 'unsafe-inline'",
                    "img-src 'self' data: https:",
                    "font-src 'self' data:",
                    "connect-src 'self' wss: https:",
                    "frame-ancestors 'self'",
                    "object-src 'none'",
                    "base-uri 'self'",
                ])
            );
        }

        return $response;
    }
}
